### ISSUE TITLE
(后端部分)npm run dev正常运行，但是npm start报错无法运行

### ISSUE THREAD

**Issue by Raudience** [hilanmiao/smart-miao#2]
![image](https://github.com/hilanmiao/smart-miao/assets/52769726/41cb9e50-6b7c-4699-bdeb-e90d7638381e)

**Comment by hilanmiao** [comment]
> ![image](https://user-images.githubusercontent.com/52769726/241693166-41cb9e50-6b7c-4699-bdeb-e90d7638381e.png)

https://www.imqianduan.com/nodejs/15.html      错误信息太少，你瞅一瞅，把错误都打印出来
